# Generated by Django 5.0.3 on 2026-05-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='flashcards',
            field=models.JSONField(default=list),
        ),
    ]
