# Generated by Django 5.0.3 on 2026-05-29 18:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0002_studymaterial_flashcards'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='share_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
