# Generated by Django 5.0.3 on 2026-06-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0004_studymaterial_is_favorite_studymaterial_mindmap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
