# Generated by Django 5.0.3 on 2026-06-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0005_studymaterial_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='is_mastered',
            field=models.BooleanField(default=False),
        ),
    ]
