# Generated by Django 5.0.3 on 2026-06-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0006_studymaterial_is_mastered'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='content_type',
            field=models.CharField(choices=[('youtube', 'YouTube Video'), ('article', 'Article')], default='youtube', max_length=10),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='video_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
